api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from api.views import UserViewSet, CourseViewSet


app_name = 'api'

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'courses', CourseViewSet)

urlpatterns = [
    url(r'^', include(router.urls))
]

courses/urls.py
from django.urls import path

from courses.views import CourseListView, CourseDetailView


app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('<int:pk>/', CourseDetailView.as_view(), name='detail'),
]

like_otus/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
    path('users/', include('users.urls')),
    path('users/', include('registration.backends.simple.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from registration.backends.simple.views import RegistrationView

from users.forms import CustomRegistrationForm

app_name = 'users'

urlpatterns = [
    path('register/',
         RegistrationView.as_view(form_class=CustomRegistrationForm),
         name='registration_register'),
    path('register/complete/',
         TemplateView.as_view(template_name='registration/registration_complete.html'),
         name='registration_complete'),
]

courses/models.py
from django.db import models
from django.conf import settings


# todo Подумать насчет запихивания модулей и уроков в json
class Course(models.Model):
    name = models.CharField(max_length=256, unique=True)
    brief = models.CharField(max_length=256, null=True)
    description = models.TextField()
    price = models.PositiveIntegerField()
    duration = models.PositiveSmallIntegerField()
    start_date = models.DateTimeField()
    load = models.CharField(max_length=256)
    logo = models.ImageField(upload_to='images/courses/', null=True, blank=True)
    tutors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='courses')
    employers = models.ManyToManyField('Employer', related_name='courses')

    def __str__(self):
        return self.name

    def get_modules_names(self):
        return [module.name for module in self.modules.all()]

    def get_employers_names(self):
        return [employer.name for employer in self.employers.all()]


class Module(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='modules')

    def __str__(self):
        return self.name


# todo Подумать насчет вынесения homework в отдельную модель
class Lesson(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    date = models.DateTimeField()
    homework = models.TextField(null=True, blank=True)
    module = models.ForeignKey(Module, on_delete=models.CASCADE, related_name='lessons')

    def __str__(self):
        return self.name


# todo Убрать blank из логотипа?
class Employer(models.Model):
    name = models.CharField(max_length=256)
    about = models.TextField()
    logo = models.ImageField(upload_to='images/employers/', blank=True)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    about = models.TextField(null=True, blank=True)
    is_student = models.BooleanField(default=False)
    is_tutor = models.BooleanField(default=False)

users/forms.py
from django.contrib.auth import get_user_model

from registration.forms import RegistrationForm

from users.models import User


class CustomRegistrationForm(RegistrationForm):
    class Meta:
        model = User
        fields = (getattr(get_user_model(), 'USERNAME_FIELD', 'username'), 'email', 'first_name', 'last_name')

api/views.py
from rest_framework import mixins, viewsets
from django.contrib.auth import get_user_model

from courses.models import Course
from api.serializers import UserSerializer, CourseSerializer


class UserViewSet(mixins.CreateModelMixin, mixins.ListModelMixin, mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer


class CourseViewSet(mixins.ListModelMixin, mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer

courses/views.py
from django.views.generic import ListView, DetailView

from courses.models import Course


class CourseListView(ListView):
    model = Course


class CourseDetailView(DetailView):
    model = Course

courses/templates/courses/course_detail.html
{% extends 'base.html' %}

{% load course_extras %}

{% block title %}
    {{ course.name }}.
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">{{ course.name }}</h1>
            <div class="row">
                <div class="col-3">
                    <strong>Стоимость:</strong> {{ course.price }} руб.
                </div>
                <div class="col-3">
                    <strong>Нагрузка:</strong> {{ course.load }}
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <strong>Продолжительность:</strong> {{ course.duration }} месяцев
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <a class="btn btn-primary btn-lg mt-3" href="#" role="button">Начать тестирование</a></p>
                </div>
                <div class="col-3">
                    <a class="btn btn-primary btn-lg mt-3" href="#" role="button">День открытых дверей</a></p>
                </div>
            </div>
        </div>
    </div>
    <nav class="nav">
        <a class="nav-link" href="#about">О курсе</a>
        <a class="nav-link" href="#syllabus">Программа</a>
        <a class="nav-link" href="#schedule">Расписание</a>
        <a class="nav-link" href="#tutors">Преподаватели</a>
        <a class="nav-link" href="#employers">Работодатели</a>
    </nav>
    <div class="container-fluid mt-2">
        <div class="row">
            <div class="col-12">
                <h2 id="about">О курсе</h2>
                {{ course.description|safe }}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h2 id="syllabus">Программа</h2>
                {% for module_name in course.get_modules_names %}
                    <h3>{{ module_name }}</h3>
                    <ul>
                    {% get_lessons_names course module_name as lessons_names %}
                    {% for lesson_name in lessons_names %}
                        <li>{{ lesson_name }}</li>
                    {% endfor %}
                    </ul>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h2 id="schedule">Расписание</h2>
                <p>
                    Занятия начинаются в {{ course.start_date|date:'l, d F H:i' }}
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h2 id="tutors">Преподаватели</h2>
                {% for tutor in course.tutors.all %}
                    <h3>{{ tutor.first_name }} {{ tutor.last_name }}</h3>
                    {{ tutor.about|safe }}
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h2 id="employers">Работодатели</h2>
                <ul>
                {% for employer_name in course.get_employers_names %}
                    <li><strong>{{ employer_name }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

courses/templates/courses/course_list.html
{% extends 'base.html' %}

{% block title %}
    Курсы.
{% endblock %}

{% block content %}
    <h1>Курсы</h1>
    <div class="album py-5 bg-light">
        <div class="container mt-5">
            <div class="row">
                {% for course in course_list %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <a href="{% url 'courses:detail' course.id %}">
                                <img class="card-img-top" src="{{ course.logo.url }}" style="height: 225px; width: 100%; display: block;">
                            </a>
                            <div class="card-body">
                                <h3 class="card-title">{{ course.name }}</h3>
                                <p class="card-text"></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <span>С {{ course.start_date|date:'d F' }} {{ course.duration }} месяцев</span>
{#                                    <button type="button" class="btn btn-sm btn-outline-secondary">Купить</button>#}
                                    <a href="{% url 'courses:detail' course.id %}" class="text-muted">Подробнее</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0059)http://getbootstrap.com/docs/4.1/examples/starter-template/ -->
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{% static 'images/favicon.png' %}">

        <title>{% block title %}{% endblock %} Like OTUS</title>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
              integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
              crossorigin="anonymous">

        <!-- Custom styles for this template -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/content.css">
    </head>

    <body data-__gyazo-extension-added-paste-support="true">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href="#">Like OTUS</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'courses:list' %}">Курсы <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Мероприятия</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Обучение</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0 ml-auto">
                    <input class="form-control mr-sm-2" type="text" placeholder="Поиск" aria-label="Поиск">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
                </form>
            </div>
        </nav>

        <main role="main" class="container-fluid">
            {% block content %}{% endblock %}
        </main><!-- /.container -->
        <footer class="footer">
            <div class="container">
                <span class="text-muted">© 2018 Like OTUS</span>
            </div>
        </footer>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
                integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
                integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
                crossorigin="anonymous"></script>
    </body>
</html>